/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as Errors401RouteImport } from './routes/_errors/401'
import { Route as Errors403RouteImport } from './routes/_errors/403'
import { Route as Errors500RouteImport } from './routes/_errors/500'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesEditorIndexRouteImport } from './routes/notes/editor/index'
import { Route as NotesEditorNoteIdRouteImport } from './routes/notes/editor/$noteId'
import { Route as NotesViewerNoteIdRouteImport } from './routes/notes/viewer/$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors401Route = Errors401RouteImport.update({
  id: '/_errors/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/_errors/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/_errors/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesEditorIndexRoute = NotesEditorIndexRouteImport.update({
  id: '/notes/editor/',
  path: '/notes/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesEditorNoteIdRoute = NotesEditorNoteIdRouteImport.update({
  id: '/notes/editor/$noteId',
  path: '/notes/editor/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesViewerNoteIdRoute = NotesViewerNoteIdRouteImport.update({
  id: '/notes/viewer/$noteId',
  path: '/notes/viewer/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/401': typeof Errors401Route
  '/403': typeof Errors403Route
  '/500': typeof Errors500Route
  '/notes/': typeof NotesIndexRoute
  '/notes/editor/$noteId': typeof NotesEditorNoteIdRoute
  '/notes/viewer/$noteId': typeof NotesViewerNoteIdRoute
  '/notes/editor/': typeof NotesEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/401': typeof Errors401Route
  '/403': typeof Errors403Route
  '/500': typeof Errors500Route
  '/notes': typeof NotesIndexRoute
  '/notes/editor/$noteId': typeof NotesEditorNoteIdRoute
  '/notes/viewer/$noteId': typeof NotesViewerNoteIdRoute
  '/notes/editor': typeof NotesEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/_errors/401': typeof Errors401Route
  '/_errors/403': typeof Errors403Route
  '/_errors/500': typeof Errors500Route
  '/notes/': typeof NotesIndexRoute
  '/notes/editor/$noteId': typeof NotesEditorNoteIdRoute
  '/notes/viewer/$noteId': typeof NotesViewerNoteIdRoute
  '/notes/editor/': typeof NotesEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/401'
    | '/403'
    | '/500'
    | '/notes/'
    | '/notes/editor/$noteId'
    | '/notes/viewer/$noteId'
    | '/notes/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/401'
    | '/403'
    | '/500'
    | '/notes'
    | '/notes/editor/$noteId'
    | '/notes/viewer/$noteId'
    | '/notes/editor'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/_errors/401'
    | '/_errors/403'
    | '/_errors/500'
    | '/notes/'
    | '/notes/editor/$noteId'
    | '/notes/viewer/$noteId'
    | '/notes/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  Errors401Route: typeof Errors401Route
  Errors403Route: typeof Errors403Route
  Errors500Route: typeof Errors500Route
  NotesIndexRoute: typeof NotesIndexRoute
  NotesEditorNoteIdRoute: typeof NotesEditorNoteIdRoute
  NotesViewerNoteIdRoute: typeof NotesViewerNoteIdRoute
  NotesEditorIndexRoute: typeof NotesEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/401': {
      id: '/_errors/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof Errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/403': {
      id: '/_errors/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/500': {
      id: '/_errors/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/editor/': {
      id: '/notes/editor/'
      path: '/notes/editor'
      fullPath: '/notes/editor/'
      preLoaderRoute: typeof NotesEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/editor/$noteId': {
      id: '/notes/editor/$noteId'
      path: '/notes/editor/$noteId'
      fullPath: '/notes/editor/$noteId'
      preLoaderRoute: typeof NotesEditorNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/viewer/$noteId': {
      id: '/notes/viewer/$noteId'
      path: '/notes/viewer/$noteId'
      fullPath: '/notes/viewer/$noteId'
      preLoaderRoute: typeof NotesViewerNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors500Route: Errors500Route,
  NotesIndexRoute: NotesIndexRoute,
  NotesEditorNoteIdRoute: NotesEditorNoteIdRoute,
  NotesViewerNoteIdRoute: NotesViewerNoteIdRoute,
  NotesEditorIndexRoute: NotesEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
