# fly.server.toml
app = "note-manager-server"
primary_region = "yyz"

[build]
dockerfile = "server/Dockerfile"

[env]
PRISMA_CLIENT_ENGINE_TYPE = "library"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_stop_machines = "off"
min_machines_running = 1

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/__info"
